### ISSUE TITLE
RETRO BLOG DEPORTEANDO

### ISSUE THREAD

**Issue by ANGYCAMPOS** [gerardog17/blog.html#1]

**Comment by ANGYCAMPOS** [comment]
Buenas Practicas:
Codigo esta indentado
Presentación de homeblog
CSS de navedagor del homeblog
Emulación correcta del Login
Versiones Evolutivas del Proyecto

RETRO:

- home
 blog
Separar el CSS  del  HTML y linkearlo, 
-  Crea una Estructura de carpetas
           1. carpeta principal dentro : 
                        carpeta css
                        carpeta imagenes
                        carpeta js
                        carpeta html (nos falta a nuestra carpeta)

**Comment by gerardog17** [comment]
Gracias
